name: Bokashi
options:
  bundleIdPrefix: com.snaka
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    MARKETING_VERSION: "0.5.0"
    CURRENT_PROJECT_VERSION: "1"
    ENABLE_HARDENED_RUNTIME: YES

packages:
  BokashiCore:
    path: Packages/BokashiCore
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0

targets:
  Bokashi:
    type: application
    platform: macOS
    sources:
      - path: Bokashi
    dependencies:
      - package: BokashiCore
      - package: KeyboardShortcuts
    info:
      path: Bokashi/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: Bokashi
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSHumanReadableCopyright: "Copyright © 2026 snaka. MIT License."
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.snaka.Bokashi
        PRODUCT_NAME: Bokashi
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Z9MLDKXDEQ
        CODE_SIGN_IDENTITY: 6070D8E483D0D6268727E48298FF9B4612B08A23
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGN_ENTITLEMENTS: Bokashi/Bokashi.entitlements
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
